### ISSUE TITLE
Side menu dropdown contents are displayed and has no slide toggle

### ISSUE THREAD

**Issue by MarkSiaga** [BlackrockDigital/startbootstrap-sb-admin-2#64] opened 2015-06-02 06:29 UTC
When i transfered the files in my laravel application, the side sub menus are already being displayed.
![untitled](https://cloud.githubusercontent.com/assets/12709022/7929828/feac0b8e-0934-11e5-9f66-fbbe4d42dd05.png)

**Comment by swjawa** [comment] 2015-06-03 08:33
I have the same problem too but only on some pages of my application. My console displays ".metisMenu is not a function" in sb-admin-2.js.
This problem occurs on five pages and the other don't have it. I don't know how to correct it.

**Comment by marcelod** [comment] 2015-06-03 11:50
This is a problem only in dashboard

**Comment by duard** [comment] 2015-07-20 22:37
Same problem here 
![screen shot 2015-07-20 at 7 36 57 pm](https://cloud.githubusercontent.com/assets/36894/8789185/ba165e9a-2f16-11e5-9acd-48699c9ce268.png)

**Comment by elysewise2076** [comment] 2015-08-26 06:34
has anyone found a solution for this?

**Comment by elysewise2076** [comment] 2015-08-26 06:39
found one myself:

add this to the top of sb-admin-2.js (before the metisMenu call)


  $("#side-menu").metisMenu({
    toggle: false
  });

**Comment by swjawa** [comment] 2015-08-26 11:44
Sorry, but that does not work for me :/

**Comment by Davidrl1000** [comment] 2015-11-02 20:35
You must to load first the file jquery.metisMenu.js, before the sb-admin-2.js

**Comment by swjawa** [comment] 2015-11-02 20:51
Yes of course, but it is now fixed for me. It was conflicts with other libraries.

**Comment by guojianlv** [comment] 2016-01-12 02:43
I found that when the URL is end with '#', like this:
http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/index.html#
then all the sidebar menus will expand automatically.

**Comment by davidtmiller** [comment] 2016-07-01 18:05
I'm going to look into reworking the entire side menu in a future release I think. The metis menu has been great but it might be time for something custom and a little more reliable.

**Comment by sdonald2** [comment] 2016-07-13 01:34
I can't really tell from the comments if this was ever solved.. I am kind of lame in the fact that I am still learning all this javascript, css and HTML nonsense :) But, I am having the exact same problem that the side menu is expanded and is staying as such.. I am not getting any errors on the console anymore, but they remain expanded.

**Comment by davidtmiller** [comment] 2016-08-19 22:34
This should be working as intended now. There aren't any errors in the console so I marking this as closed for now. If you find any other errors feel free to open a new issue!

**Closed by davidtmiller** 2016-08-19 22:34 UTC
Labels: bug

**Comment by anandsutar** [comment] 2018-02-05 13:06
[_Navigation.cshtml.zip](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/files/1695179/_Navigation.cshtml.zip)

I got the same issue found while browsing the page.
, the side sub menus are already being displayed.
i have make corrected sequence while writing the code.
